#define WIFI_SSID "BYU-WiFi" //BYU-WiFi
#define WIFI_PASSWORD ""
#define MQTT_SERVER "broker.escapeos.com"
#define MQTT_USER "byupe_s25"
#define MQTT_PASSWORD "cognitive17-Rhythm-ascend-preservation"
#define BASE_STATION_CLIENT_ID "eOS-baseGroup1"
#define PUZZLE_CLIENT_ID "eOS-puzzleGroup1"
#define BASE_STATION_TOPIC "test-base_station"
#define COMMAND_TOPIC "eOS-puzzleGroup1-command"
#define SHOW_DEBUG "true"
